spring.application.name=pyeong

spring.datasource.url=jdbc:postgresql://localhost:5432/pyeong
spring.datasource.username=postgres
spring.datasource.password=gksdldks153$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
